stages:
  preprocess:
    cmd: python src/data_preparation.py
    deps:
      - src/data_preparation.py
      - data/raw
    outs:
      - data/processed

  train:
    cmd: python src/train.py
    deps:
      - src/train.py
      - data/processed
    outs:
      - models/baseline_cnn.pt
